---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-provider
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-provider
  template:
    metadata:
      labels:
        app: payment-provider
        part-of: challenge
        component: backend
    spec:
      containers:
      - name: main
        image: payment-provider:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: payment-prov
            containerPort: 8082
        livenessProbe:
          httpGet:
            path: /healthz
            port: payment-prov
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1042
        runAsGroup: 1042
---
apiVersion: v1
kind: Service
metadata:
  name: payment-provider
  labels:
    app: payment-provider
    part-of: challenge
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: payment-provider
