---
apiVersion: v1
kind: Service
metadata:
  name: payment-provider
  labels:
    app: payment-provider
    part-of: challenge
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: payment-provider
