---
apiVersion: v1
kind: Service
metadata:
  name: invoice-app
  labels:
    app: invoice-app
    part-of: challenge
    component: frontend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: invoice-app
